# Generated by Django 4.2.4 on 2023-09-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
